from typing import Protocol
from sqlalchemy.orm import Session
from ..models import User, Workload
from ..schemas import JobSpec, DebugSpec

ACTIVE = {"STARTING", "RUNNING"}
TERMINAL = {"COMPLETED", "FAILED", "CANCELLED", "TIMED_OUT", "REJECTED"}


class SchedulerBackend(Protocol):
    def submit_train(self, db: Session, user: User, spec: JobSpec) -> Workload: ...
    def start_debug(self, db: Session, user: User, spec: DebugSpec) -> Workload: ...
    def cancel(self, db: Session, resource: Workload) -> None: ...
    def get_status(self, db: Session, resource_id: str) -> Workload | None: ...
    def list_resources(self, db: Session) -> list: ...
    def tick(self, db: Session) -> None: ...
